language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t dgdocker2021/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dgdocker2021/docker-react npm run test -- --coverage
