
version: '2.4'
services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./src/App.js:/app/src/App.js
      - ./src/App.test.js:/app/src/App.test.js

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/App.js:/app/src/App.js
      - ./src/App.test.js:/app/src/App.test.js
    command: ["npm", "run", "test"]
    